---
driver:
  name: ssh_gzip
  hostname: SERVER_IP
  username: root
#  port:
#  password:
#  ssh_key:

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu

suites:
  - name: default
    data_bags_path: "../data_bags"
    run_list:
      - recipe[clodoo]
    attributes:
      trust_root: false
