networks:
  default:
    external:
      name: vd
services:
  metabase:
    description: metabase is Web tools for BI with dashboard
    optional: True
    image: metabase/metabase
    network_mode: "bridge"
    environment:
    - MB_DB_FILE=/file/metabase.db
    links:
    - db
    volumes:
    - .:/file
  pgadmin:
    description: Pgadmin v4 is postgresql Web GUI
    optional: True
    image: fenglc/pgadmin4
    links:
      - db
  adminer:
    optional: RDBMS Web GUI (including Postgresql) with usability and performance
    image: adminer
    links:
      - db
  db:
    environment:
    - POSTGRES_USER=odoo
    - POSTGRES_DB=db
    image: akretion/voodoo-postgresql
    volumes:
    - .db/data/:/var/lib/postgresql/data
    - .db/socket/:/var/run/postgresql/
  mailcatcher:
    description: Mailcatcher is a fake mail server
    optional: True
    image: akretion/lightweight-mailcatcher
  odoo:
    image: akretion/voodoo:latest
    environment:
    - PYTHONDONTWRITEBYTECODE=True
    links:
    - db
    volumes:
    - .:/workspace
    - .db/socket/:/var/run/postgresql/
version: '2'
